# Generated by Django 4.2.7 on 2026-06-06 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlerSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('base_url', models.URLField()),
                ('crawl_config', models.JSONField(help_text='Правила извлечения: {"list_selector": "...", "item_selector": "...", "fields": {"title": "css", ...}, "next_page_selector": "..."}')),
                ('schedule', models.CharField(default='0 * * * *', help_text='Cron строка (например, "0 * * * *")', max_length=100)),
                ('status', models.CharField(choices=[('active', 'Активен'), ('disabled', 'Отключён'), ('error', 'Ошибка')], default='active', max_length=20)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExternalOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, max_length=200)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('new', 'Новый'), ('actual', 'Актуальный'), ('archived', 'Архивный'), ('error', 'Ошибка обработки')], default='new', max_length=20)),
                ('suspicious', models.BooleanField(default=False)),
                ('moderation_note', models.TextField(blank=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='external_meta', to='orders.order')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crawler.crawlersource')),
            ],
        ),
        migrations.CreateModel(
            name='CrawlerLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(max_length=20)),
                ('orders_found', models.IntegerField(default=0)),
                ('orders_updated', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crawler.crawlersource')),
            ],
        ),
    ]
